print('What is your name?')
name = input()
print('How old are you?')
age = input()
print('Where are you live?')
place = input()
print(('This is'), str(name))
print(('It is'), str(age))
print(('She/He live in'), str(place))